---
# https://kubernetes.io/docs/setup/independent/high-availability/
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "172.16.20.10:6443"
networking:
  dnsDomain: "cluster.local"
  podSubnet: "10.32.0.0/12"
  serviceSubnet: "10.32.0.0/12"
---
kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
mode: userspace
